#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    hostname: localhost
#springdoc:
#  swagger-ui:
##    path: /swagger-ui.html
##    display-request-duration: true
##    groups-order: DESC
##    operationsSorter: method
#    disable-swagger-default-url: true
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true